export const INCREMENT_ENTHUSIASM = "INCREMENT_ENTHUSIASM"; // 增加热忱度
export type T_INCREMENT_ENTHUSIASM = typeof INCREMENT_ENTHUSIASM;

export const DECREMENT_ENTHUSIASM = "DECREMENT_ENTHUSIASM"; // 减少热忱度
export type T_DECREMENT_ENTHUSIASM = typeof DECREMENT_ENTHUSIASM;
